apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-frontend
  template:
    metadata:
      labels:
        app: fitness-frontend
    spec:
      containers:
        - name: fitness-frontend
          image: quantumempress/fitness-tracker-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-frontend-service
spec:
  selector:
    app: fitness-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Exposes on localhost
