apiVersion: v1
kind: Secret
metadata:
  name: fitness-tracker-secrets
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb+srv://okaforomalicha98:fimdqWWWIKjX01Gh@fitnesstrackercluster.89dxetw.mongodb.net/fitness_tracker_db?retryWrites=true&w=majority"
  APP_JWT_SECRET: "FitnessTrackerSecretKeyForJwtTokenGenerationShouldBeLongEnough"
  APP_JWT_EXPIRATION_MS: "86400000"
  CLOUDINARY_CLOUD_NAME: "didjosym5"
  CLOUDINARY_API_KEY: "266322942279777"
  CLOUDINARY_API_SECRET: "uCi6K0gqnFq91GWd6kaqdahwOeQ"
